- name: Check if cargo is installed
  command: command -v cargo
  register: cargo_exists
  ignore_errors: true

- name: Download Rustup Installer
  when: force_install | default(false) | bool or cargo_exists is failed
  get_url:
    url: "{{ rust.installer_url }}"
    dest: "{{ rust.installer_dest }}"
    mode: "{{ rust.installer_mode }}"
    force: "{{ force_download }}"

- name: Install Rust & Cargo
  when: force_install | default(false) | bool or cargo_exists is failed
  shell: "{{ rust.installer_dest }} {{ rust.installer_args }}"
