---
extends: default

rules:
  line-length:
    max: 200
    level: warning

  indentation:
    spaces: 2
    indent-sequences: true

  comments:
    min-spaces-from-content: 1

  comments-indentation: disable

  document-start: disable

  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']

ignore: |
  .github/
  venv/
  .venv/
  node_modules/
