- name: Bootstrap local development environment
  hosts: local
  roles:
    - role: bootstrap
      tags: [bootstrap]

    - role: zsh
      tags: [zsh, bootstrap]

    - role: docker
      tags: [docker]

    - role: node
      tags: [node]

    - role: chrome
      tags: [chrome, bootstrap]

    - role: vscode
      tags: [vscode, bootstrap]

    - role: slack
      tags: [slack, bootstrap]

    - role: fonts
      tags: [fonts, bootstrap]

    - role: dotfiles
      tags: [dotfiles]

    - role: rust
      tags: [rust, bootstrap]
