- name: Bootstrap local development environment
  hosts: local

  # Tag each role so that we can select individual roles to run
  # with ansible-playbook --tags
  roles:
    - role: various
      tags: [various]

    - role: docker
      tags: [docker]

    - role: dotfiles
      tags: [dotfiles]

    - role: node
      tags: [node]

    - role: chrome
      tags: [chrome]

