- name: Bootstrap local development environment
  hosts: local

  # Tag each role so that we can select individual roles to run
  # with ansible-playbook --tags
  roles:
    - role: bootstrap
      tags: [bootstrap]

    - role: zsh
      tags: [zsh, bootstrap]

    - role: docker
      tags: [docker]

    - role: node
      tags: [node]

    - role: yarn
      tags: [yarn, node]

    - role: chrome
      tags: [chrome, app, bootstrap]

    - role: vscode
      tags: [vscode, app, bootstrap]

    - role: insomnia
      tags: [insomnia, app, bootstrap]

    - role: spotify
      tags: [spotify, app, bootstrap]

    - role: dotfiles
      tags: [dotfiles]
