- name: Install GNU Stow
  apt:
    name:
      - "{{ stow.package_name }}"
    state: "{{ stow.package_state }}"
  become: true

- name: Build .dotfiles list
  vars:
    user_home: "{{ lookup('env', 'HOME') }}"
  ansible.builtin.find:
    paths: ["{{ user_home }}/{{ dotfiles.base_path }}/{{ dotfiles.source_dir }}"]
    recurse: no
    file_type: directory
  register: files
  failed_when: false
  become: false

- name: Deploy .dotfiles
  with_items: '{{ files.files }}'
  vars:
    user_home: "{{ lookup('env', 'HOME') }}"
    package_name: "{{ item.path | basename }}"
    is_force: "{{ force_install | default(false) | bool }}"
  environment:
    STOW_DIR: "{{ user_home }}/{{ dotfiles.base_path }}/{{ dotfiles.source_dir }}"
  shell: >
    stow {{ stow_command.target_option }} {{ user_home }}
    {% if is_force %}--restow{% endif %}
    {{ stow_command.stow_option }} {{ package_name }}
    || true
  when:
    - files is not skipped
    - files.files is defined
    - files.files | length > 0
  changed_when: false
  become: false
