- name: Check if VSCode is installed
  command: command -v code
  register: vscode_exists
  failed_when: false
  changed_when: false

- name: Remove existing VSCode installation for force install
  apt:
    name: "{{ vscode.package_name }}"
    state: absent
  become: true
  when: force_install | default(false) | bool and vscode_exists.rc == 0
  ignore_errors: true

- name: Remove VSCode repository for force install
  apt_repository:
    repo: "{{ vscode.repo_url }}"
    state: absent
  become: true
  when: force_install | default(false) | bool
  ignore_errors: true

- name: Remove VSCode GPG key for force install
  file:
    path: "{{ vscode.gpg_dest }}"
    state: absent
  become: true
  when: force_install | default(false) | bool
  ignore_errors: true

- name: Check if VSCode GPG key exists
  stat:
    path: "{{ vscode.gpg_dest }}"
  register: vscode_key_exists

- name: Ensure /etc/apt/keyrings directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
    owner: root
    group: root
  become: true
  when: force_install | default(false) | bool or not vscode_key_exists.stat.exists

- name: Ensure gnupg is installed (needed to dearmor keys)
  apt:
    name: gnupg
    state: present
  become: true
  when: force_install | default(false) | bool or not vscode_key_exists.stat.exists

- name: Download VSCode GPG key (ASCII) to temporary file
  get_url:
    url: "{{ vscode.gpg_url }}"
    dest: /tmp/packages.microsoft.asc
    mode: '0644'
    force: true
  become: true
  when: force_install | default(false) | bool or not vscode_key_exists.stat.exists

- name: Convert VSCode GPG key to binary and move to keyrings
  command: gpg --dearmor --yes --output {{ vscode.gpg_dest }} /tmp/packages.microsoft.asc
  args:
    creates: "{{ vscode.gpg_dest }}"
  become: true
  when: force_install | default(false) | bool or not vscode_key_exists.stat.exists

- name: Re-check VSCode key exists
  stat:
    path: "{{ vscode.gpg_dest }}"
  register: vscode_key_exists
  become: true
  changed_when: false
  failed_when: false

- name: Set permissions on VSCode keyring
  file:
    path: "{{ vscode.gpg_dest }}"
    mode: "{{ vscode.gpg_mode }}"
    owner: root
    group: root
  become: true
  when: vscode_key_exists.stat.exists

- name: Remove temporary VSCode key file
  file:
    path: /tmp/packages.microsoft.asc
    state: absent
  become: true
  when: force_install | default(false) | bool or not vscode_key_exists.stat.exists

- name: Check if VSCode repository exists
  shell: grep -q "packages.microsoft.com/repos/code" /etc/apt/sources.list.d/*.list || true
  register: vscode_repo_exists
  failed_when: false
  changed_when: false

- name: Add VSCode repository
  apt_repository:
    repo: "{{ vscode.repo_url }}"
    state: present
  become: true
  when: force_install | default(false) | bool or vscode_repo_exists.rc != 0

- name: Update apt cache after adding VSCode repo
  apt:
    update_cache: yes
  become: true
  when: force_install | default(false) | bool or vscode_repo_exists.rc != 0

- name: Install VSCode
  apt:
    name:
      - "{{ vscode.package_name }}"
    state: "{{ package_state }}"
    update_cache: "{{ update_cache }}"
  become: true
  when: force_install | default(false) | bool or vscode_exists.rc != 0
  register: vscode_install
  ignore_errors: true

- name: Display VSCode installation warning
  debug:
    msg: "Warning: VSCode package not available in repository. Skipping installation."
  when: vscode_install is failed

- name: Set default editor
  shell: |
    {{ default_editor.command }}
  changed_when: false
  become: false
  when: vscode_install is succeeded
