- name: Check if VSCode is installed
  shell: command -v code
  register: vscode_exists
  failed_when: false
  changed_when: false

- name: Remove existing VSCode installation for force install
  apt:
    name: "{{ vscode.package_name }}"
    state: absent
  become: true
  when: force_install | default(false) and vscode_exists.rc == 0
  ignore_errors: true

- name: Remove VSCode repository for force install
  apt_repository:
    repo: "{{ vscode.repo_url }}"
    state: absent
  become: true
  when: force_install | default(false)
  ignore_errors: true

- name: Remove VSCode GPG key for force install
  file:
    path: "{{ vscode.gpg_dest }}"
    state: absent
  become: true
  when: force_install | default(false)
  ignore_errors: true

- name: Check if VSCode GPG key exists
  stat:
    path: "{{ vscode.gpg_dest }}"
  register: vscode_key_exists

- name: Add VSCode GPG apt key
  get_url:
    url: "{{ vscode.gpg_url }}"
    dest: "{{ vscode.gpg_dest }}"
    mode: "{{ vscode.gpg_mode }}"
    force: true
  become: true
  when: force_install | default(false) or not vscode_key_exists.stat.exists

- name: Check if VSCode repository exists
  shell: grep -q "packages.microsoft.com/repos/vscode" /etc/apt/sources.list.d/*.list || true
  register: vscode_repo_exists
  failed_when: false
  changed_when: false

- name: Add VSCode repository
  apt_repository:
    repo: "{{ vscode.repo_url }}"
    state: present
  become: true
  when: force_install | default(false) or vscode_repo_exists.rc != 0

- name: Install VSCode
  apt:
    name:
      - "{{ vscode.package_name }}"
    state: "{{ package_state }}"
    update_cache: "{{ update_cache }}"
  become: true
  when: force_install | default(false) or vscode_exists.rc != 0

- name: Set default editor
  shell: |
    {{ default_editor.command }}
  changed_when: false
  become: false

