---
# Docker configuration variables

# Docker required packages
docker_required_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  - python3-pip
  - virtualenv
  - python3-setuptools

# Docker packages to install
docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

# Docker repository configuration
docker_repository:
  gpg_url: "https://download.docker.com/linux/ubuntu/gpg"
  # Use the apt keyrings directory and keep the key as .asc (readable by apt)
  gpg_dest: "/etc/apt/keyrings/docker.asc"
  gpg_mode: "0644"
  # repo_url is the base URL; tasks will construct the full deb line with arch and codename
  repo_url: "https://download.docker.com/linux/ubuntu"

# Package state configuration
package_state: "latest"
update_cache: true

# User configuration
docker_group: "docker"
