---
- name: Check if zoxide is installed
  command: command -v zoxide
  register: zoxide_exists
  failed_when: false
  changed_when: false

- name: Install zoxide
  shell: |
    set -euo pipefail
    curl -fsSL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh
  args:
    executable: /bin/bash
  when: force_install | default(false) | bool or zoxide_exists.rc != 0
