- name: Check if Zsh is installed
  shell: command -v zsh
  register: zsh_exists
  failed_when: false
  changed_when: false

- name: Install Zsh
  apt:
    name:
      - zsh
    update_cache: yes
  become: yes
  when: zsh_exists.rc != 0

- name: Create ~/.zsh directory
  become: no
  file:
    path: "~/.zsh"
    state: directory
    mode: 0755

- name: Check if zsh-syntax-highlighting exists
  stat:
    path: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
  register: zsh_highlighting_exists

- name: Install zsh-highlighting
  become: no
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    force: yes
    version: master
  when: not zsh_highlighting_exists.stat.exists

- name: Check if zsh-autosuggestions exists
  stat:
    path: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  register: zsh_autosuggestions_exists

- name: Install zsh-autosuggestions
  become: no
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    force: yes
    version: master
  when: not zsh_autosuggestions_exists.stat.exists

- name: Check oh-my-zsh installed
  stat:
    path: ~/.oh-my-zsh
  register: ohmyzsh

- name: Install oh-my-zsh
  become: no
  shell:
    cmd: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: not ohmyzsh.stat.exists

- name: Check if powerlevel10k theme exists
  stat:
    path: ~/.oh-my-zsh/custom/themes/powerlevel10k
  register: powerlevel10k_exists

- name: Install zsh powerlevel10k theme
  become: no
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: ~/.oh-my-zsh/custom/themes/powerlevel10k
    force: yes
    version: master
  when: not powerlevel10k_exists.stat.exists

- name: Check if nx-completion exists
  stat:
    path: ~/.oh-my-zsh/custom/plugins/nx-completion
  register: nx_completion_exists

- name: Install nx-completion
  become: no
  git:
    repo: https://github.com/jscutlery/nx-completion.git
    dest: ~/.oh-my-zsh/custom/plugins/nx-completion
    force: yes
    version: main
  when: not nx_completion_exists.stat.exists
  tags: [nx-completion]

- name: Check if you-should-use plugin exists
  stat:
    path: ~/.oh-my-zsh/custom/plugins/you-should-use
  register: you_should_use_exists

- name: Install you-should-use plugin
  become: no
  git:
    repo: https://github.com/MichaelAquilina/zsh-you-should-use.git
    dest: ~/.oh-my-zsh/custom/plugins/you-should-use
    force: yes
    version: master
  when: not you_should_use_exists.stat.exists

- name: Check if zsh-completions exists
  stat:
    path: ~/.oh-my-zsh/custom/plugins/zsh-completions
  register: zsh_completions_exists

- name: Install zsh-completions
  become: no
  git:
    repo: https://github.com/zsh-users/zsh-completions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-completions
    force: yes
    version: master
  when: not zsh_completions_exists.stat.exists
