---
# Spotify Installation Tasks - Direct download method

- name: Check if Spotify is already installed
  shell: dpkg -l | grep -q spotify-client && echo "installed" || echo "not installed"
  register: spotify_installed
  failed_when: false
  changed_when: false

- name: Create download directory
  file:
    path: "/tmp/spotify_install"
    state: directory
    mode: "0755"
  when: spotify_installed.stdout == "not installed" or (force_install | default(false))

- name: Download Spotify .deb package
  get_url:
    url: "https://repository-origin.spotify.com/pool/non-free/s/spotify-client/spotify-client_1.2.60.564.gcc6305cb_amd64.deb"
    dest: "/tmp/spotify_install/spotify.deb"
    mode: "0644"
  register: spotify_download
  when: spotify_installed.stdout == "not installed" or (force_install | default(false))

- name: Remove repository file if it exists
  file:
    path: "/etc/apt/sources.list.d/spotify.list"
    state: absent
  become: true
  when: spotify_installed.stdout == "not installed" or (force_install | default(false))

- name: Install Spotify dependencies
  apt:
    name:
      - libssl-dev
      - libcurl4-gnutls-dev
      - libglib2.0-0
      - libgtk-3-0
      - libxss1
      - libdbus-1-3
    state: present
  become: true
  when: spotify_installed.stdout == "not installed" or (force_install | default(false))

- name: Install Spotify from downloaded .deb
  apt:
    deb: "/tmp/spotify_install/spotify.deb"
    state: present
  become: true
  when: (spotify_installed.stdout == "not installed" or (force_install | default(false))) and spotify_download is defined and spotify_download.changed

- name: Clean up temporary files
  file:
    path: "/tmp/spotify_install"
    state: absent
  when: spotify_installed.stdout == "not installed" or (force_install | default(false))
