---
# Spotify Installation Tasks - Direct download method


# Spotify Installation Tasks - Snap method

- name: Ensure snapd is installed
  apt:
    name: snapd
    state: present
    update_cache: yes
  become: true

- name: Install Spotify via snap
  community.general.snap:
    name: spotify
    state: present
  become: true
