- name: Check if Google Chrome is installed
  command: command -v google-chrome
  register: chrome_exists
  failed_when: false
  changed_when: false

- name: Remove existing Chrome installation for force install
  apt:
    name: "{{ chrome.package_name }}"
    state: absent
  become: true
  when: force_install | default(false) | bool and chrome_exists.rc == 0
  ignore_errors: true

- name: Remove Chrome repository for force install
  apt_repository:
    repo: "{{ chrome.repo_url }}"
    state: absent
  become: true
  when: force_install | default(false) | bool
  ignore_errors: true

- name: Remove Chrome GPG key for force install
  file:
    path: "{{ chrome.gpg_dest }}"
    state: absent
  become: true
  when: force_install | default(false) | bool
  ignore_errors: true

- name: Check if Chrome GPG key exists
  stat:
    path: "{{ chrome.gpg_dest }}"
  register: chrome_key_exists

- name: Ensure /etc/apt/keyrings directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
    owner: root
    group: root
  become: true
  when: force_install | default(false) | bool or not chrome_key_exists.stat.exists

- name: Ensure gnupg is installed (needed to dearmor keys)
  apt:
    name: gnupg
    state: present
  become: true
  when: force_install | default(false) | bool or not chrome_key_exists.stat.exists

- name: Download Google signing key (ASCII) to temporary file
  get_url:
    url: "{{ chrome.gpg_url }}"
    dest: /tmp/google-linux-signing-key.pub
    mode: '0644'
    force: true
  become: true
  when: force_install | default(false) | bool or not chrome_key_exists.stat.exists

- name: Convert Google signing key to binary and move to keyrings
  command: gpg --dearmor --yes --output {{ chrome.gpg_dest }} /tmp/google-linux-signing-key.pub
  args:
    creates: "{{ chrome.gpg_dest }}"
  become: true
  when: force_install | default(false) | bool or not chrome_key_exists.stat.exists

- name: Re-check Google key exists
  stat:
    path: "{{ chrome.gpg_dest }}"
  register: chrome_key_exists
  become: true
  changed_when: false
  failed_when: false

- name: Set permissions on Google keyring
  file:
    path: "{{ chrome.gpg_dest }}"
    mode: "{{ chrome.gpg_mode }}"
    owner: root
    group: root
  become: true
  when: chrome_key_exists.stat.exists

- name: Remove temporary Google key file
  file:
    path: /tmp/google-linux-signing-key.pub
    state: absent
  become: true
  when: force_install | default(false) | bool or not chrome_key_exists.stat.exists

- name: Find existing Google repo files (if any)
  shell: grep -l "dl.google.com" /etc/apt/sources.list.d/*.list 2>/dev/null || true
  register: google_repo_files
  failed_when: false
  changed_when: false

- name: Normalize Signed-By path in existing Google repo files
  replace:
    path: "{{ item }}"
    regexp: 'signed-by=[^\]]+'
    replace: 'signed-by=/etc/apt/keyrings/google.gpg'
  loop: "{{ google_repo_files.stdout_lines }}"
  when: google_repo_files.stdout_lines | length > 0
  become: true

- name: Check if Chrome repository exists
  shell: grep -q "dl.google.com/linux/chrome/deb" /etc/apt/sources.list.d/*.list || true
  register: chrome_repo_exists
  failed_when: false
  changed_when: false

- name: Add repository Google Chrome repository
  apt_repository:
    repo: "{{ chrome.repo_url }}"
    state: present
  become: true
  when: force_install | default(false) | bool or chrome_repo_exists.rc != 0

- name: Install Google Chrome
  apt:
    name: "{{ chrome.package_name }}"
    update_cache: "{{ update_cache }}"
    state: "{{ package_state }}"
  become: true
  when: force_install | default(false) | bool or chrome_exists.rc != 0
