- name: Check if Google Chrome is installed
  shell: command -v google-chrome
  register: chrome_exists
  failed_when: false
  changed_when: false

- name: Check if Chrome GPG key exists
  stat:
    path: "{{ chrome.gpg_dest }}"
  register: chrome_key_exists

- name: Add repository key
  get_url:
    url: "{{ chrome.gpg_url }}"
    dest: "{{ chrome.gpg_dest }}"
    mode: "{{ chrome.gpg_mode }}"
    force: true
  become: yes
  when: not chrome_key_exists.stat.exists

- name: Check if Chrome repository exists
  shell: grep -q "dl.google.com/linux/chrome/deb" /etc/apt/sources.list.d/*.list || true
  register: chrome_repo_exists
  failed_when: false
  changed_when: false

- name: Add repository Google Chrome repository
  apt_repository:
    repo: "{{ chrome.repo_url }}"
    state: present
  become: yes
  when: chrome_repo_exists.rc != 0

- name: Install Google Chrome
  apt:
    name: "{{ chrome.package_name }}"
    update_cache: "{{ update_cache }}"
    state: "{{ package_state }}"
  become: yes
  when: chrome_exists.rc != 0
