---
- name: Add repository key
  get_url:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    dest: /etc/apt/trusted.gpg.d/chrome.asc
    mode: '0644'
    force: true
  become: yes
  
- name: Add repository Google Chrome repository
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    state: present
  become: yes

- name: Install Google Chrome
  apt:
    name: google-chrome-stable
    update_cache: yes
    state: latest
  become: yes
