- name: Add Yarn apt key
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
  become: yes

- name: Add Yarn repository
  apt_repository:
    repo: "deb https://dl.yarnpkg.com/debian/ stable main"
    filename: yarn
  become: yes

- name: Install Yarn
  apt:
    name: yarn
    update_cache: yes
  become: yes
