- name: Install Node.js
  apt: 
    name: 
      - nodejs
      - npm
    state: present

- name: Install npm global packages
  become: true
  npm:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default('latest') }}"
    global: true
    state: latest
  with_items: "{{ npm_global_packages }}"

- name: Switch to latest Node.js LTS version
  become: true
  command: n lts