- name: Check if Node.js is installed
  shell: command -v node
  register: node_exists
  failed_when: false
  changed_when: false

- name: Check if npm is installed
  shell: command -v npm
  register: npm_exists
  failed_when: false
  changed_when: false

- name: Install Node.js
  apt:
    name: "{{ nodejs_packages }}"
    state: "{{ package_state }}"
  become: yes
  when: node_exists.rc != 0 or npm_exists.rc != 0

- name: Install npm global packages
  npm:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(npm_package_version) }}"
    global: true
    state: latest
  become: true
  with_items: "{{ npm_global_packages }}"
  tags: [npm-global]

- name: Switch to latest Node.js LTS version
  command: "{{ node_lts_command }}"
  become: true
  tags: [switch-to-node-lts]

- name: Enable Corepack
  command: "{{ corepack_command }}"
  become: true

- name: Check Bun installed
  shell: command -v bun
  register: bun_exists
  ignore_errors: yes
  tags: [bun]

- name: Install Bun
  get_url:
    url: "{{ bun.install_url }}"
    dest: "{{ bun.install_script }}"
    mode: "{{ bun.script_mode }}"
    force: 'yes'
  when: bun_exists.rc != 0
  tags: [bun]

- name: Install Bun
  shell: "{{ bun.install_script }}"
  when: bun_exists.rc != 0
  tags: [bun]
