- name: Install Node.js
  apt:
    name:
      - nodejs
      - npm
    state: present
  become: yes

- name: Install npm global packages
  become: true
  npm:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default('latest') }}"
    global: true
    state: latest
  with_items:
    - nx
    - '@angular/cli'
    - http-server
    - n
    - diff-so-fancy
  tags: [npm-global]

- name: Switch to latest Node.js LTS version
  become: true
  command: n lts
  tags: [switch-to-node-lts]

- name: Enable Corepack
  become: true
  command: corepack enable

- name: Check Bun installed
  shell: command -v bun
  register: bun_exists
  ignore_errors: yes
  tags: [bun]

- name: Install Bun
  when: bun_exists is failed
  get_url:
    url: https://bun.sh/install
    dest: /tmp/bun-install.sh
    mode: '0755'
    force: 'yes'
  tags: [bun]

- name: Install Bun
  when: bun_exists is failed
  shell: /tmp/bun-install.sh
  tags: [bun]
