- name: Install Docker required packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest
    update_cache: true
  become: yes

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present
  become: yes

- name: Install docker-ce and docker-compose-plugin
  apt:
    name:
      - docker-ce
      - docker-compose-plugin
    state: latest
    update_cache: true
  become: yes

#- name: Ensure Docker service is enabled and started.
#  service:
#    name: docker
#    state: started
#    enabled: yes

#- name: Ensure Docker users are in the Docker group.
#  user:
#    name
