---
# Terraform configuration variables

# Terraform repository configuration
terraform:
  gpg_url: "https://apt.releases.hashicorp.com/gpg"
  gpg_dest: "/etc/apt/trusted.gpg.d/hashicorp.asc"
  gpg_mode: "0644"
  repo_url: "deb [arch=amd64] https://apt.releases.hashicorp.com focal main"
  package_name: "terraform"
  required_packages:
    - gnupg
    - software-properties-common

# Package configuration
package_state: "latest"
update_cache: true
