---
# Terraform configuration variables

# Terraform configuration for the new HashiCorp installation method
terraform:
  gpg_url: "https://apt.releases.hashicorp.com/gpg"
  gpg_dest: "/usr/share/keyrings/hashicorp-archive-keyring.gpg"
  gpg_mode: "0644"
  package_name: "terraform"
  required_packages:
    - gnupg
    - software-properties-common
    - wget
    - curl

# Package configuration
package_state: "latest"
update_cache: true
