- name: Create fonts directory
  become: no
  file:
    path: "{{ fonts.local_dir }}"
    state: directory
    mode: "{{ fonts.dir_mode }}"

- name: Check existing fonts
  become: no
  find:
    paths: "{{ fonts.local_dir }}"
    patterns: "*"
  register: existing_fonts

- name: Get source fonts
  become: no
  find:
    paths: "{{ fonts.source_dir }}"
    patterns: "*"
  register: source_fonts

- name: Install fonts
  become: no
  copy:
    remote_src: yes
    src: "{{ item.path }}"
    dest: "{{ fonts.local_dir }}/{{ item.path | basename }}"
  with_items: "{{ source_fonts.files }}"
  when:
    - source_fonts.files | length > 0
    - item.path | basename not in (existing_fonts.files | map(attribute='path') | map('basename') | list)
  register: fonts_installed

- name: Clear fonts cache
  become: no
  shell: |
    {{ font_cache.command }}
  when: fonts_installed is changed

